# From http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/142072

@name="AdBouncer"

@content_types=[/(.*)/]

# From http://easylist.adblockplus.org/adblock_rick752.txt
# Parsed as of 7 Dec 2007. While we could update this list
# fresh every time Alchemy is run, we don't want to risk
# inserting bad code. So we statically add the block list.

+ /&adspace=/
+ /-adspace/
+ /&affiliate=/
+ /&ClientType=(.*)&AdID=/
+ /&partner/
+ /\?ad_id=/
+ /\?affiliate/
+ /\?getad=&/
+ /\?showbanner=/
+ /_ad.aspx/
+ /_adbrite/
+ /_ads\//
+ /_adspace/
+ /_banner_ad/
+ /_bannerid(.*)random/
+ /_files\/(.*).htm/
+ /adaffiliate/
+ /adcounter/
+ /admentor/
+ /ads.sv.publicus./
+ /adsfac.net/
+ /affiliatebrand./
+ /audienceprofiler./
+ /aurora-(.*)marketing.co/
+ /bannerad/
+ /BannerMangement/
+ /blog.tmcnet.(.*)\/overlib.js/
+ /brandcentral./
+ /capitalnews9.com\/images\/geo_/
+ /Click(.*)Advertiser/
+ /clicktag=(.*)\/ad/
+ /content.search/
+ /cppops(.*)nextag/
+ /cubics.com\//
+ /dbbsrv.com/
+ /dgmaustralia./
+ /download-door.search.com\/search/
+ /dynamicad./
+ /earthlink(.*)\/promos/
+ /eas.blocket./
+ /engine.awaps.net\//
+ /exitexplosion.(.*)\/exit.js/
+ /faireagle.com/
+ /favinfo.com\/ad./
+ /geocities.com\/js_source\//
+ /google.com(.*)adfetch/
+ /google.com(.*)\/promo_/
+ /hera.hardocp./
+ /i.azjmp./
+ /imageshack(.*)tagworld/
+ /interclick./
+ /js2.yimg.(.*)_popup_/
+ /kanoodle/
+ /link_ads/
+ /mediacorpsingapore/
+ /medrx.sensis.com.au\/content\//
+ /nebuad.com/
+ /network.ninemsn.(.*)\/share\//
+ /openbanner/
+ /page.grabclick./
+ /phpadsnew/
+ /popinads./
+ /popunder/
+ /popup_ad/
+ /precisionclick./
+ /pro-market./
+ /promopop/
+ /ptnrcontent/
+ /publicidad/
+ /quigo.com/
+ /rad.live.com\/ADSAdClient/
+ /richmedia.(.*)yimg./
+ /sponslink/
+ /sponsor.gif/
+ /sponsorads/
+ /sponsoredlink/
+ /sponsored_links/
+ /sponsors(.*)banner/
+ /storefronts/
+ /sys-con.com\/common\//
+ /targetpoint.com/
+ /textlink-ads./
+ /themis.yahoo./
+ /trafficlayer.de/
+ /vs20060817.com\//
+ /worsethanfailure.(.*)\/Tizes\//
+ /xcelsiusadserver./
+ /yceml.net/
+ /.1100i.com\//
+ /.112.2o7./
+ /.122.2o7./
+ /.188server./
+ /.2mdn.net\//
+ /.360ads./
+ /.43plc.com/
+ /.about.com\/0\//
+ /.ad.tomshardware./
+ /.ad-flow./
+ /.ad4cash./
+ /.adaction./
+ /.adbrite.com\//
+ /.adbureau./
+ /.adbutler./
+ /.adcentriconline./
+ /.adengage./
+ /.adfusion./
+ /.adgardener./
+ /.adgroups./
+ /.adhese./
+ /.adicate./
+ /.adition.com\//
+ /.adinterax./
+ /.adireland./
+ /.adjuggler./
+ /.admarketplace./
+ /.adnet.biz/
+ /.adnet.ru/
+ /.adocean./
+ /.adpark./
+ /.adserver./
+ /.adshuffle./
+ /.adsmarket./
+ /.adsonar./
+ /.adspeed./
+ /.adtech.de\//
+ /.adtext./
+ /.adtmedia./
+ /.adverserve./
+ /.advertarium./
+ /.adverti/
+ /.advertserve./
+ /.afcyhf./
+ /.affiliate./
+ /.affiliatefuel./
+ /.affiliatefuture./
+ /.affiliatesensor./
+ /.aim4media./
+ /.akamai.(.*)sponsor/
+ /.anrdoezrs./
+ /.arcadebanners./
+ /.assoc-amazon./
+ /.atdmt.com\//
+ /.atwola./
+ /.auspipe./
+ /.awin1.com/
+ /.awltovhc./
+ /.axill.com\//
+ /.azads.com\//
+ /.bannerconnect./
+ /.bannersmania./
+ /.belointeractive./
+ /.bestofferdirect./
+ /.bidvertiser./
+ /.bimedia.net\/video\//
+ /.blogads./
+ /.bluestreak./
+ /.bravenetmedianetwork./
+ /.bravenet.(.*)\/rover\//
+ /.bridgetrack./
+ /.burstnet./
+ /.c8.net.ua\//
+ /.casalemedia./
+ /.cc-dt.com\//
+ /.centralmediaserver./
+ /.checkm8./
+ /.checkmystats./
+ /.chitika./
+ /.cjt1.net/
+ /.clash-media./
+ /.claxonmedia./
+ /.clickad./
+ /.clickbooth/
+ /.clickintext./
+ /.clickthrucash./
+ /.connextra./
+ /.contextweb./
+ /.cpaclicks/
+ /.cpmstar./
+ /.crashextads./
+ /.crispads./
+ /.decisionmark./
+ /.deepmetrix./
+ /.directorym./
+ /.dl-rms.com\//
+ /.domainsponsor./
+ /.doubleclick./
+ /.dpbolvw./
+ /.ebayrtm.com\/rtm\?RtmCmd&a=inline&/
+ /.ebaystatic.(.*)\/adsense./
+ /.edge.ru4./
+ /.etology./
+ /.euroclick./
+ /.exponential./
+ /.extreme-dm./
+ /.eyewonder./
+ /.fairfax./
+ /.falkag./
+ /.fastclick./
+ /.feedburner.com\/~a\//
+ /.fimserve./
+ /.fixionmedia./
+ /.fmpub.net\//
+ /.forrestersurveys./
+ /.ftjcfx./
+ /.fluxads./
+ /.flyordie.com\/games\/free\/b\/(.*)--\?p=/
+ /.funklicks./
+ /.game-advertising-online./
+ /.gamersbanner./
+ /.gcion.com/
+ /.geopromos./
+ /.gestionpub./
+ /.gklmedia./
+ /.go.com\/(.*)ads.js/
+ /.haymarketmedia./
+ /.henwo.com\//
+ /.hit-now./
+ /.httpool./
+ /.hypemakers./
+ /.hypervre./
+ /.ic-live./
+ /.icdirect./
+ /.imglt.com\//
+ /.impresionesweb./
+ /.imrworldwide./
+ /.indiads./
+ /.industrybrains./
+ /.inetinteractive./
+ /.infocious./
+ /.intellitxt./
+ /.interpolls./
+ /.ivwbox./
+ /.jdoqocy./
+ /.jydesign./
+ /.ketoo.com\//
+ /.klipmart./
+ /.kontera./
+ /.kqzyfj./
+ /.leadacceptor./
+ /.lduhtrp./
+ /.linkexchange./
+ /.linkworth./
+ /.maxserving./
+ /.mb01.com\//
+ /.mbn.com.ua\//
+ /.mediaonenetwork./
+ /.mediaplex./
+ /.mediavantage./
+ /.mercuras./
+ /.metaffiliation./
+ /.miva.com\//
+ /.moneymakers.de\//
+ /.mootermedia./
+ /.myway.com\/gca_iframe./
+ /.netavenir./
+ /.newanglemedia.com\/clients\//
+ /.newsadstream./
+ /.northmay./
+ /.nwsource.(.*)\/adv.gif/
+ /.nyadmcncserve-/
+ /.obibanners./
+ /.onenetworkdirect./
+ /.overture./
+ /.oxado.com\//
+ /.peelawayads.com\/affads\//
+ /.perfb.com/
+ /.pheedo./
+ /.php\?(.*)bannerid/
+ /.php\?adclass/
+ /.platinumadvertisement./
+ /.pointroll./
+ /.pricespy.co.nz\/adds\//
+ /.primaryads./
+ /.pro-advertising./
+ /.probannerswap./
+ /.profitpeelers./
+ /.projectwonderful./
+ /.qksrv.net\//
+ /.qksz.net\//
+ /.questionmarket./
+ /.revresda./
+ /.revsci./
+ /.rmxads./
+ /.rottentomatoes.(.*)size=(.*)x(.*)&dechannel/
+ /.rovion.(.*)\?AffID=/
+ /.scanscout./
+ /.shareasale./
+ /.shareresults./
+ /.smartadserver./
+ /.smarttargetting./
+ /.snap.com\//
+ /.sonnerie./
+ /.space.com\/promo\//
+ /.specificclick./
+ /.specificmedia./
+ /.sponsorpalace./
+ /.spotplex.(.*)widget/
+ /.sta-ads./
+ /.survey-poll./
+ /.tacoda./
+ /.targetnet./
+ /.tiser.com/
+ /.tkqlhce./
+ /.torrentspy.(.*)staticframe/
+ /.tqlkg.com/
+ /.tradedoubler./
+ /.trafic./
+ /.tribalfusion./
+ /.typepad.com\/sponsors\//
+ /.tyroo./
+ /.unicast./
+ /.utarget./
+ /.valueclick./
+ /.vibrantmedia./
+ /.vpico.com\//
+ /.webads.co.nz/
+ /.webmasterplan./
+ /.widgetbucks./
+ /.worlddatinghere./
+ /.xchangebanners./
+ /.yimg.com\/a\//
+ /.yimg.com\/adv\//
+ /.zangocash.(.*)\/detectenvironment/
+ /.zeads.com\//
+ /.zedo.com\//
+ /\/63.225.61./
+ /\/64.73.24.44/
+ /217.15.94.117/
+ /\/ad\/(.*)promo/
+ /\/ad\/code/
+ /\/ad.asp\?/
+ /\/ad\/frame/
+ /\/ad\/mercury/
+ /\/ad_/
+ /\/ad_functions/
+ /\/ad_insert./
+ /\/ad_refresher./
+ /\/ad_(.*).gif/
+ /\/adbanner/
+ /\/adbrite/
+ /\/adbrite./
+ /\/adclick/
+ /\/adcode.js/
+ /\/adcycle\/(.*)/
+ /\/adframe./
+ /\/adgraphics\/(.*)/
+ /\/AdIFrame./
+ /\/adimages\/(.*)/
+ /\/adfunction/
+ /\/adimage./
+ /\/adinsert./
+ /\/adjs.php\?/
+ /\/adjsmp.php\?/
+ /\/adlabel/
+ /\/adlinks.js/
+ /\/ad_manager.js/
+ /\/admanager/
+ /\/adpeeps\/(.*)/
+ /\/Adplayer\/(.*)/
+ /\/adRelated./
+ /\/adrevolver\/(.*)/
+ /\/ads.htm/
+ /\/ads.php\?/
+ /\/ads(.*).php/
+ /\/ads2.php\?/
+ /\/ads\/(.*)/
+ /\/ads2\/(.*)/
+ /\/AdsIframe\/(.*)/
+ /\/AdsManager\/(.*)/
+ /\/adscripts\/(.*)/
+ /\/adspro\/(.*)/
+ /\/ADSAdClient31.dll\?GetAd\?/
+ /\/adscript./
+ /\/adsense_/
+ /\/adserver/
+ /\/adshow\?/
+ /\/adsonar./
+ /\/adSwap.js/
+ /\/adtags\/(.*)/
+ /\/adtext./
+ /\/adtext_/
+ /\/adtraff./
+ /\/advert_/
+ /\/advert\/ms/
+ /\/adverti/
+ /\/adverts\/(.*)/
+ /\/adview./
+ /\/AdWorks\/(.*)/
+ /\/adx.js/
+ /\/affiliates.babylon./
+ /\/AffiliateWiz\/(.*)/
+ /\/aj.600z./
+ /\/ajs.php\?/
+ /\/autoPromo/
+ /\/banimpress./
+ /\/banman\/(.*)/
+ /\/banmanpro\/ad/
+ /\/banner.php\?(.*)http/
+ /\/banner_file.php\?/
+ /\/bannermedia\/(.*)/
+ /\/banners\/(.*)/
+ /\/banners.adultfriendfinder/
+ /\/banners\/banner/
+ /\/banners\/(.*)clickTAG/
+ /\/banners\/(.*).gif/
+ /\/bannery\/(.*)\?banner=/
+ /\/bbc.com\/script\/1\/config.js/
+ /\/blogad_/
+ /\/blogads/
+ /\/bmp\/banman.asp\?/
+ /\/bs.yandex.ru/
+ /\/cas.clickability.com\/(.*)/
+ /\/cm8adam/
+ /\/cnnSLads.js/
+ /\/cnwk.(.*)widgets.js/
+ /\/commercials\/splash/
+ /\/csDynamic/
+ /\/ctxtlink\/(.*)/
+ /\/de(.*).myspace./
+ /\/descPopup.js/
+ /\/directads./
+ /\/dontblockthis\/(.*)/
+ /\/DisplayAds/
+ /\/DynamicAd\?/
+ /\/ebayinternalpromos\/(.*)/
+ /\/ekmas.com/
+ /\/flashAds./
+ /\/flashbanner\/(.*)/
+ /\/flipmedia/
+ /\/freetrafficbar./
+ /\/fuseads\/(.*)/
+ /\/gamecast\/ads/
+ /\/getad.php\?/
+ /\/get_ad.php\?/
+ /\/getbanner.cfm\?/
+ /\/googleAd.js/
+ /\/google-adsense/
+ /\/hits4pay./
+ /\/houseads\/(.*)/
+ /\/iframead./
+ /\/iframed_(.*)sessionid=/
+ /\/images\/ad\/(.*)/
+ /\/IndianRailways\/(.*)/
+ /\/intext.js/
+ /\/itunesaffiliate/
+ /\/kermit.macnn./
+ /\/launch\/testdrive.gif/
+ /\/layer-ads./
+ /\/LinkExchange\/(.*)/
+ /\/linkshare\/(.*)/
+ /\/loadAdWiz.js/
+ /\/logos\/adLogo/
+ /\/lw\/ysc_csc_/
+ /\/marketing(.*)partner/
+ /\/mac-ad\?/
+ /\/media\/(.*)promo/
+ /\/media.funpic.(.*)\/layer./
+ /\/mediamgr/
+ /\/nascar\/(.*)\/defector.js/
+ /\/oas_logic./
+ /\/oasc03./
+ /\/oascentral./
+ /\/oasisi-j.php\?/
+ /\/overture_/
+ /\/partner\/(.*)\?/
+ /\/partner(.*)rotate/
+ /\/partners\/(.*)/
+ /\/partnership\/(.*)affiliate/
+ /\/peel.js/
+ /\/peelad\/(.*)/
+ /\/phpads\/(.*)/
+ /\/phpadserver\/(.*)/
+ /\/popupjs./
+ /\/promos\/(.*)/
+ /\/promos\/(.*)promo/
+ /\/printads\/(.*)/
+ /\/public\/ad\?/
+ /\/r.mail.ru/
+ /\/rad.(.*)\?GetSAd=/
+ /\/rotation\/(.*).php\?/
+ /\/rtq.careerbuilder./
+ /\/shared\/promos\/(.*)/
+ /\/showads./
+ /\/showbanner.php\?/
+ /\/small_ad./
+ /\/socialads.js/
+ /\/Splash\/Page_Header\/(.*)/
+ /\/spinbox.freedom./
+ /\/sponsImages\/(.*)/
+ /\/storyAds./
+ /\/surveyCookie.js/
+ /\/textAd.js/
+ /\/trusearch.net\/affblock\/(.*)/
+ /\/userbanners\/(.*)/
+ /\/vendshow\/(.*)/
+ /\/videoads./
+ /\/w1.buysub./
+ /\/webadImg\/(.*)/
+ /\/webads_/
+ /\/ygames_e\/embed\/src\/embedPlayer.js/
+ /\/ysmads.html/
+ /\/\/wrapper.3dgamers./
+ /http:\/\/171.66.124.80\//
+ /http:\/\/196.41.0.207\//
+ /http:\/\/72.32.71.244/
+ /http:\/\/a.ads./
+ /http:\/\/ad(.*).emidiate./
+ /http:\/\/abm.hothardware./
+ /http:\/\/ad-uk./
+ /http:\/\/ad./
+ /http:\/\/ad0./
+ /http:\/\/ad1./
+ /http:\/\/adclient/
+ /http:\/\/adcreative./
+ /http:\/\/adfarm./
+ /http:\/\/adimg./
+ /http:\/\/adimages./
+ /http:\/\/adinterax./
+ /http:\/\/adq./
+ /http:\/\/adremote./
+ /http:\/\/adonline./
+ /http:\/\/ads./
+ /http:\/\/ads1./
+ /http:\/\/ads2./
+ /http:\/\/ads3./
+ /http:\/\/ads4./
+ /http:\/\/ads5./
+ /http:\/\/adsatt./
+ /http:\/\/adsearch./
+ /http:\/\/adserv/
+ /http:\/\/adsnew./
+ /http:\/\/adsremote./
+ /http:\/\/adstream.(.*).cgi/
+ /http:\/\/adsvr./
+ /http:\/\/adsys./
+ /http:\/\/adt./
+ /http:\/\/adtology/
+ /http:\/\/adv./
+ /http:\/\/advert./
+ /http:\/\/adverts./
+ /http:\/\/adworks./
+ /http:\/\/adx./
+ /http:\/\/affiliates.(.*).aspx\?/
+ /http:\/\/afimages./
+ /http:\/\/almobty.com\//
+ /http:\/\/altfarm./
+ /http:\/\/avpa./
+ /http:\/\/banner./
+ /http:\/\/banners.(.*)http/
+ /http:\/\/bin-layer.de\//
+ /http:\/\/body.imho.ru\//
+ /http:\/\/bwp./
+ /http:\/\/cdn.nvero./
+ /http:\/\/circads./
+ /http:\/\/common.(.*)\/slider.js/
+ /http:\/\/feeds.(.*)\/~a\//
+ /http:\/\/fdads.sv./
+ /http:\/\/ffxcam./
+ /http:\/\/getad./
+ /http:\/\/images.(.*)\/banners\//
+ /http:\/\/jazad./
+ /http:\/\/lads.(.*)-gutter-/
+ /http:\/\/mads./
+ /http:\/\/marketing.(.*)http/
+ /http:\/\/ng3.ads./
+ /http:\/\/oas-central./
+ /http:\/\/pagead2./
+ /http:\/\/pagead2.(.*)\?/
+ /http:\/\/partner./
+ /http:\/\/promo./
+ /http:\/\/promo2./
+ /http:\/\/promos./
+ /http:\/\/promote./
+ /http:\/\/rcm.amazon./
+ /http:\/\/reklama./
+ /http:\/\/richmedia2./
+ /http:\/\/rss.(.*)\/~a\//
+ /http:\/\/servedbyadbutler./
+ /http:\/\/smartad./
+ /http:\/\/stocker.bonnint./
+ /http:\/\/synad./
+ /http:\/\/ttsrc.aroq./
+ /http:\/\/video.flashtalking./
+ /http:\/\/(.*)\/partners./
- /1800flowers.com\/(.*)\/banners\//
- /abc.go.com\/streaming\/move(.*)\/player.html\?/
- /.adbrite.gif/
- /ads1.msn.com\/library\/dap.js/
- /ads.ign.com\/(.*)masthead/
- /\/ads\/video\/(.*).flv/
- /.adserver.yahoo.com\/(.*)=HEAD&/
- /(.*)\/autoplayer\/(.*)/
- /.brightcove.com(.*)\/viewer\//
- /.cbc.ca\/includes\/promos\//
- /cdn.fastclick.net\/fastclick.net\/video\//
- /compusa.com(.*)\/banners\//
- /cosmos.bcst.yahoo.com\/scp_v3\//
- /DartShellPlayer/
- /discovery.com\/realmedia/
- /discovery.com/
- /doubleclick.net(.*)video(.*)player/
- /doubleclick.net\/adj\/(.*)video/
- /.doubleclick.net\/crossdomain.xml/
- /doubleclick.net\/pfadx\/sw.nol\//
- /eq2i.com\/abbt./
- /\/espn360\/banner\?/
- /flyordie.com\/(.*)&affiliate/
- /.forbes.com(.*)\/video/
- /fox(.*).com(.*)video/
- /.gametrailers.(.*)player/
- /.ifilm.com\/(.*)spike-functions.js\?/
- /int1.fp.sandpiper.net\//
- /judo.salon.com\//
- /meevee.com\/ads\/adIframe.aspx\?/
- /.menshealth.com\/cda\/js\/coremetrics\//
- /microsoft.com\/(.*)\/banners\//
- /.nbc.com\/(.*)\/video\//
- /(.*)\/nbcu.nbc\/(.*)/
- /\/nbcu.cnbc\/video/
- /.nbl.com.au\/(.*)\/0(.*)-image./
- /newsimg.bbc.co.uk\/media\/(.*)promo/
- /nissanusa.com\//
- /nytimes.com\/ads\/mm/
- /rad.live.com\/(.*)&DPJS/
- /RealMedia\/(.*)_video\//
- /RealMedia\/(.*).flv/
- /.sears.com\/data\//
- /snopes.com(.*)\/advertisements\//
- /.space.com\/flashvideo\//
- /.stream.aol.com/
- /techreport.com\/ads\//
- /thenewsroom.com\/mash\/options\//
- /\?(.*)torrentreactor.net/
- /.tvguide.com\/script\/webtrends.js/
- /vidavee.net(.*)video/
- /video.on.nytimes.com\//
- /videos.theonion./
- /video.wwe.com/
- /yahoo.com\/a\?(.*)headr/
- /.yimg.com\/a\/1-\/java\/promotions\/js\/ad_/
- /http:\/\/ads.biggerboat.com\//
- /http:\/\/ads1.msn.com(.*)=video/
- /http:\/\/(.*)economist.com\//
- /http:\/\/www.nbc.com\/Video\//
- /http:\/\/www.nfl.com\/videos/
- /http:\/\/promo.ebay.(.*)\?GetCrossPromos/
- /http:\/\/(.*)userplane.com\/chatlite\/run\//
- /http:\/\/(.*)videodetective.com\//
- /http:\/\/video.(.*).flv/
- /http:\/\/(.*).wikimedia.org\/wikipedia\//

def apply(req, res)
	res.body=""
end